### ISSUE TITLE
Attribute _size is of type uint64

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/libSplash#266]
Various attributes are given as unit64 type. This might be slightly more memory efficient but causes a lot of trouble when using the common openPMD data analysis tools, because e.g. when loading `_size` to perform a data slicing via integer division as
```python
Ny = f[...].attrs['_size'][1]
data_slice = f[...][:, Ny//2, :]
```
will fail because a integer division by a `uint` and an `int` is just a floating point division in python.

I would vote for changing theses types to ints. Any other suggestions how to solve this?

**Comment by PrometheusPi** [comment]
cc @steindev and @alex-koe

**Comment by ax3l** [comment]
@PrometheusPi the attributes with `_` are not openPMD and are only in libSplash files for legacy reasons. please use the according openPMD attributes instead.

Decisions for unsigned vs. signed are usually not done due to memory constrains but due to definition range. A size can never be negative for example.

Array access and behavior of integer arithmetics differs on the Python version. In any case, you can always cast your access to the array indices:
```python
data_slice = f[...][:, int(Ny//2), :]
```

**Comment by ax3l** [comment]
Python 2.7 and 3.4 possibilities for the numpy cast handling:
```python
import numpy as np

np.uint(3)//2
# 1.0
# correct int division, just upcasted to float (which numpy indexes do not like)

np.uint(3)/2
# 1.5
# proper float division (which numpy indexes do not like)

np.floor_divide(np.uint(3), 2, dtype=np.int)
# 1
# proper numpy mixed int math

N = f[...].attrs['_size'].astype(np.int64)
Ny = N[1]
data_slice = f[...][:, Ny//2, :]
# convert on read
```

I personally would prefer `int(Ny)//2` or if necessary the last method. This is still "just" a Numpy specific thing and not really a question of the actually stored data attribute.

**Comment by PrometheusPi** [comment]
Further investigations showed that only the `np.uint64` data type is effected. I opened an [issue](https://github.com/numpy/numpy/issues/9833) at the numpy repo. 

This seems to be a python issue - I will thus close this issue here.

**Comment by PrometheusPi** [comment]
**Update:**
In numpy, casting to float is intentional at this point. Since uint has a slightly higher range, a cast to int might lead to errors. Thus `unitX // intX` will always return `int(X*2)`. However, since `unit64` is the largest rang available, there a cast to float is favored to avoid possible errors. 

Thus, numpy will not change this behavior.

**Comment by PrometheusPi** [comment]
The optimal solution is thus:
```python
Ny // np.uint(2)
```

**Comment by ax3l** [comment]
Thx for asking upstream!

Actually the decision of going to float for a slightly larger range (2x) is bought by getting less precision due to the mantissa in floats. This can only be counter-act again by going to really large floats, which is memory and speed costly when starting from a `(u)int64`...
